- name: Create projects in openstack
  vexxhost.atmosphere.project:
    name: "{{ _project.name }}"
    domain: "{{ _ks_domain.name }}"
  when: _project.name is defined
  loop: "{{ _ks_domain.projects }}"
  loop_control:
    loop_var: _project
  register: _projects

- name: Create parent group for openstack projects
  community.general.keycloak_group:
    realm: "{{ _ks_domain.name }}"
    name: openstack-projects

- name: Create keycloak group for each project
  community.general.keycloak_group:
    realm: "{{ _ks_domain.name }}"
    name: "{{ _project.name }}"
    parents:
      - name: openstack-projects
  when: _project.name is defined
  loop: "{{ _ks_domain.projects }}"
  loop_control:
    loop_var: _project

- name: Assign member role to domain for openstack-projects keycloak group
  vexxhost.atmosphere.role_assignment:
    domain: "{{ _ks_domain.name }}"
    group: openstack-projects
    role: member

- name: Assign roles to projects
  vexxhost.atmosphere.role_assignment:
    domain: "{{ _ks_domain.name }}"
    project: "{{ _project.name }}"
    group: "{{ _project.name }}"
    role: member
  when: _project.name is defined
  loop: "{{ _ks_domain.projects }}"
  loop_control:
    loop_var: _project

- name: Set project quotas
  vexxhost.atmosphere.quota:
    name: "{{ _projects.results[index].project.id }}"
    backup_gigabytes: "{{ _project.quota.backup_gigabytes | default(keystone_project_default_quota_backup_gigabytes) }}"
    backups: "{{ _project.quota.backups | default(keystone_project_default_quota_backups) }}"
    cores: "{{ _project.quota.cores | default(keystone_project_default_quota_cores) }}"
    fixed_ips: "{{ _project.quota.fixed_ips | default(keystone_project_default_quota_fixed_ips) }}"
    floating_ips: "{{ _project.quota.floating_ips | default(keystone_project_default_quota_floating_ips) }}"
    floatingip: "{{ _project.quota.floatingip | default(keystone_project_default_quota_floatingip) }}"
    gigabytes: "{{ _project.quota.gigabytes | default(keystone_project_default_quota_gigabytes) }}"
    injected_file_size: "{{ _project.quota.injected_file_size | default(keystone_project_default_quota_injected_file_size) }}"
    injected_files: "{{ _project.quota.injected_files | default(keystone_project_default_quota_injected_files) }}"
    injected_path_size: "{{ _project.quota.injected_path_size | default(keystone_project_default_quota_injected_path_size) }}"
    instances: "{{ _project.quota.instances | default(keystone_project_default_quota_instances) }}"
    key_pairs: "{{ _project.quota.key_pairs | default(keystone_project_default_quota_key_pairs) }}"
    loadbalancer: "{{ _project.quota.loadbalancer | default(keystone_project_default_quota_loadbalancer) }}"
    metadata_items: "{{ _project.quota.metadata_items | default(keystone_project_default_quota_metadata_items) }}"
    per_volume_gigabytes: "{{ _project.quota.per_volume_gigabytes | default(keystone_project_default_quota_per_volume_gigabytes) }}"
    pool: "{{ _project.quota.pool | default(keystone_project_default_quota_pool) }}"
    port: "{{ _project.quota.port | default(keystone_project_default_quota_port) }}"
    properties: "{{ _project.quota.properties | default(keystone_project_default_quota_properties) }}"
    ram: "{{ _project.quota.ram | default(keystone_project_default_quota_ram) }}"
    security_group_rule: "{{ _project.quota.security_group_rule | default(keystone_project_default_quota_security_group_rule) }}"
    security_group: "{{ _project.quota.security_group | default(keystone_project_default_quota_security_group) }}"
    server_group_members: "{{ _project.quota.server_group_members | default(keystone_project_default_quota_server_group_members) }}"
    server_groups: "{{ _project.quota.server_groups | default(keystone_project_default_quota_server_groups) }}"
    snapshots: "{{ _project.quota.snapshots | default(keystone_project_default_quota_snapshots) }}"
    volumes: "{{ _project.quota.volumes | default(keystone_project_default_quota_volumes) }}"
    volumes_types:
      volumes_lvm: "{{ _project.quota.volumes_lvm | default(keystone_project_default_quota_volumes_lvm) }}"
    snapshots_types:
      snapshots_lvm: "{{ _project.quota.snapshots_lvm | default(keystone_project_default_quota_snapshots_lvm) }}"
    gigabytes_types:
      gigabytes_lvm: "{{ _project.quota.gigabytes_lvm | default(keystone_project_default_quota_gigabytes_lvm) }}"
  loop: "{{ _ks_domain.projects }}"
  when: _project is defined
  loop_control:
    loop_var: _project
    index_var: index
